name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: ['*']

jobs:
  build:

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Check coding standards
        if: matrix.node-version == '18.x' && matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Test
        run: npm run ci
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node-${{ matrix.node-version }}
          path-to-lcov: ./coverage/lcov.info
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage/lcov.info
          parallel-finished: true
